apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-addons
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: /run/desktop/mnt/host/c/Users/HP/Desktop/Odoo/volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
