apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odoo-statefulset
  labels:
    app: odoo-app
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: odoo-app
  template:
    metadata:
      name: odoo-pod
      labels:
        app: odoo-app
    spec:
      containers:
        - name: odoo-container
          image: odoo:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres.local
            - name: PORT
              value: "30007"
            - name: POSTGRES_DB
              value: odoo-db
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
          volumeMounts:
            - mountPath: "/mnt/extra-addons"
              name: pvc-odoo-addons
            - mountPath: "/etc/odoo"
              name: pvc-odoo-config
            - mountPath: "/var/lib/odoo"
              name: pvc-odoo-web-data

  volumeClaimTemplates:
    - metadata:
        name: pvc-odoo-addons
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: storageclass-odoo-addons

    - metadata:
        name: pvc-odoo-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: storageclass-odoo-config

    - metadata:
        name: pvc-odoo-web-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: storageclass-odoo-web-data
